defaults:
  - sindy: base
  - _self_ # ショートカット定義は最後に設定


sindy:
  datasets:
    dt: 0.01
  train_comp_identifier: soma

hydra:
  run:
    dir: hydra-outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra-multiruns/${now:%Y-%m-%d_%H-%M-%S}
  sweeper:
    params:
      sindy.optimizer.alpha: 0.01, 0.05, 0.1, 0.5, 1.0