# @package _global_
surrogate:
  meta:
    comp_type: hh  # 置換対象のコンパートメント種類
    surrogate_type: sindy
    preprocessor_type: pca
    n_components: 2  # 潜在方程式の次元
    datasets:
      model_name: hh
      current_type: train
  ansatz:
    library_specs:
      - type: hh_gate_forward
      - type: hh_gate_backward
      - type: hh_gate_forward_product
      - type: hh_gate_backward_product
      - type: basis
