hh:
  params:
    _target_: neurosurrogate.dataset_utils.hh.hh_simulator.HH_Params
  transform:
    u:
      ind: "I_ext"
      sel: {}

hh3:
  params:
    _target_: neurosurrogate.dataset_utils.hh.hh_simulator.ThreeComp_Params
    G_12: ${g_12}
    G_23: ${g_23}
    G_LEAK: 0.3
    E_LEAK: -54.4
    C: 1.0
    DT: 0.01
  transform:
    u:
      ind: "I_internal"
      sel:
        direction: "soma"