hh:
  params:
  plot:
    _target_: neurosurrogate.plots.plot_hh


hh3:
  params:
    G_12: ${g_12}
    G_23: ${g_23}
    G_LEAK: 0.3
    E_LEAK: -54.4
    C: 1.0
    DT: 0.01

  plot:
    _target_: neurosurrogate.plots.plot_3comp_hh