hh:
  params:
  simulator:
    _target_: neurosurrogate.dataset_utils.hh.hh_simulator.hh_simulate
  plot:
    _target_: neurosurrogate.plots.plot_hh
  transform:
    u:
      ind: "I_ext"
      sel: {}

hh3:
  params:
    G_12: ${g_12}
    G_23: ${g_23}
    G_LEAK: 0.3
    E_LEAK: -54.4
    C: 1.0
    DT: 0.01
  simulator:
    _target_: neurosurrogate.dataset_utils.hh.hh_simulator.threecomp_simulate
  plot:
    _target_: neurosurrogate.plots.plot_3comp_hh
  transform:
    u:
      ind: "I_internal"
      sel:
        direction: "soma"