init:
  datasets:
    model_name: hh
    current:
      type: train
      params: {}
fit:
  preprocessor:
    type: pca
  library_specs:
    - type: hh_gate
    - type: hh_gate_product
    - type: basis
